# Generated by Django 4.2.6 on 2023-10-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('davlat', models.CharField(blank=True, max_length=50, null=True)),
                ('jins', models.CharField(blank=True, choices=[('Male', 'Male'), ('Famale', 'Famale')], max_length=10, null=True)),
                ('tugilgan_sana', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('davomiylik', models.CharField(max_length=100)),
                ('narx', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('janr', models.CharField(blank=True, choices=[('Fantastik', 'Fantastik'), ('Ilmiy', 'Ilmiy'), ('Tarixiy', 'Tarixiy'), ('Badiiy', 'Badiiy'), ('Komediya', 'Komediya')], max_length=20, null=True)),
                ('yil', models.DateField(blank=True, null=True)),
                ('aktyorlar', models.ManyToManyField(to='filmApp.aktyor')),
            ],
        ),
    ]
